### ISSUE TITLE
Práctica 6

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipo-evelin#2]
[PRACTICA6_Mejorado.pdf](https://github.com/user-attachments/files/17300107/PRACTICA6_Mejorado.pdf)

**Comment by Ariadnamonserrat10** [comment]
12 / 20 por que describe mas como se hace la plataforma y no como es el proceso en si

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
